### PR TITLE
Sound debug, configurable volume option.

### LINKED ISSUE #99: Sounds are not working.
The sound feature of the plugin is not working. I'm using the latest build, with a working and valid sound effect on 1.16.5.

### PR DESCRIPTION
**Pull request by KoxSosen**
Added a debug message & an option to kill your players ears while teleporting. Also closes #99 .

### CODE REVIEW

File: src/main/java/net/poweredbyhate/wildtp/WildTPListener.java [hunk 1]
```diff
@@ -1,9 +1,6 @@
 package net.poweredbyhate.wildtp;
 
-import org.bukkit.Bukkit;
-import org.bukkit.Location;
-import org.bukkit.Sound;
-import org.bukkit.World;
+import org.bukkit.*;
```
Comment (RoboMWM) [inline src/main/java/net/poweredbyhate/wildtp/WildTPListener.java:3]: I'd like to avoid wildcard statements but I may let it slide cuz dis b a yolo code plogen

File: src/main/java/net/poweredbyhate/wildtp/WildTPListener.java [hunk 2]
```diff
@@ -42,26 +39,29 @@ private void onPreTeleport(PreWildTeleportEvent ev) {
...
     private void onPostTele(PostWildTeleportEvent ev) {
-        Location lok   = ev.wildLing.getLocation();
-        World    plaza = lok.getWorld();
+        Location lok = ev.wildLing.getLocation();
+        World plaza = lok.getWorld();
 
         TeleportGoneWild.cure(ev.wildLing);
 
-        if (ev.wc.doCommandz)
-        {
```
Comment (RoboMWM) [inline src/main/java/net/poweredbyhate/wildtp/WildTPListener.java:51]: muh newlines

File: src/main/java/net/poweredbyhate/wildtp/WildTPListener.java [hunk 3]
```diff
@@ -42,26 +39,29 @@ private void onPreTeleport(PreWildTeleportEvent ev) {
...
         String sound = WildTP.instace.getConfig().getString("Sound");
         if (sound == null || sound.isEmpty())
             return;
 
         try
         {
-            plaza.playSound(lok, Sound.valueOf(sound), 1, 1);
+            String volume = WildTP.instace.getConfig().getString("Volume");
+            plaza.playSound(lok, Sound.valueOf(sound), SoundCategory.MASTER, Float.parseFloat(String.valueOf(volume)), 1);
+            WildTP.debug("Playing da sound of " + sound + " with volume of " + volume);
```
Comment (RoboMWM) [inline src/main/java/net/poweredbyhate/wildtp/WildTPListener.java:64]: ah, I see I already did have a debug in the catch. Heh.

**Review by RoboMWM — APPROVED** [review]

**Comment by RoboMWM** [comment]
> an option to kill your players ears while teleporting.

If only. Anything greater than 1 just increases radius not dB unfortunately.

File: src/main/java/net/poweredbyhate/wildtp/WildTPListener.java (hunk 1 above)
Comment (KoxSosen) [reply src/main/java/net/poweredbyhate/wildtp/WildTPListener.java:3]: IntellJ beeing a dum dum again, fixing it an other pr.

File: src/main/java/net/poweredbyhate/wildtp/WildTPListener.java (hunk 3 above)
Comment (KoxSosen) [reply src/main/java/net/poweredbyhate/wildtp/WildTPListener.java:64]: > > an option to kill your players ears while teleporting.
> 
> If only. Anything greater than 1 just increases radius not dB unfortunately.

Huh, gotta update that then.
